"""empty message

Revision ID: 37d28b324b7b
Revises: c25b1e6dab84
Create Date: 2023-09-23 08:34:06.551514

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '37d28b324b7b'
down_revision = 'c25b1e6dab84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('external_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'external_id')
    # ### end Alembic commands ###
