"""empty message

Revision ID: d39cb3f5d197
Revises: 540b79f364ae
Create Date: 2023-07-21 19:50:23.747848

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd39cb3f5d197'
down_revision = '540b79f364ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('file_connections', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'file_connections')
    # ### end Alembic commands ###
