"""empty message

Revision ID: f0beaaad1e5d
Revises: 54a57631821c
Create Date: 2023-06-27 19:59:08.959726

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f0beaaad1e5d'
down_revision = '54a57631821c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
